config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'pages#home'
get 'blog', to: 'pages#blog'
get 'about', to: 'pages#about'
get 'signup', to: 'users#new'
resources :users, except: [:new]

get 'log', to: 'sessions#new'
post 'log', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user

    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 3, maximum: 5000}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    before_save { self.email.downcase! }
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length:
     {minimum: 3, maximum: 13}
    VALID_EMAIL_REGEX = /.+\@.+\..r/i

     validates :email, presence: true, uniqueness: { case_sensitive: false }, format:
     { with: VALID_EMAIL_REGEX } 

     has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = User.first

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def blog
end

def about
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        render 'new'
    end

    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
      @users = User.all
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = "Nouvel utilisateur #{@user.username} crée "
        redirect_to articles_path
      else
        render 'new'
      end
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = "Utilisateur modifié avec succès"
        redirect_to articles_path
      else
        render 'edit'
      end
    end
  
    def show
      @user = User.find(params[:id])
    end
  
  
  
  
    private
      def user_params
        params.require(:user).permit(:username, :email, :password)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 200})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Informations</th>
      <th>Actions</th>
    </tr>
  </thead>

  
    <% obj.each do |article| %>
      <tr>
        <td><%= link_to article.title, article_path(article) %></td>
        <td><%= truncate(article.description, length: 60) %></td>
        <td><small> Crée par <strong> <%= article.user.username if article.user %></strong> depuis
          <%= time_ago_in_words(article.created_at) %> Dernière mise à jour : <%= time_ago_in_words(article.updated_at)%> </td>
        <td><%= link_to 'Edit', edit_article_path(article), class:"btn btn-xs btn-danger" %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  
</table>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |form| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
            <%= form.label :title %>
        </div>
        <div class="col-sm-10">
            <%= form.text_field :title, class: "form-control", placeholder: "Titre de l'article" %>
        </div>
      </div>

    <div class="form-group">
          <div class="col-sm-2 control-label">
            <%= form.label :description %>
          </div>
          <div class="col-sm-10">
            <%= form.text_area :description,rows: 10, class: "form-control", placeholder: "Contenu de l'article" %>
          </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit class:" btn btn-default" %>
        </div>
      </div>
    <% end %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
      <p id="notice"><%= notice %></p>

<h1>Articles</h1>
<p><%= link_to 'New Article', new_article_path %></p>

<%= render 'articles', obj: @articles %>
  </div>
</div>

<br>

app/views/articles/new.html.erb
<h1>Nouvel Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">
  <div class= "col-xs-offset-3 col-xs-9">
    <h2>  <%= @article.title %></h2>

    <div class= "well col-xs-6">
        <p> <%= @article.description %> </p>

      <div class="article-actions">
        <%= link_to 'Modifier', edit_article_path(@article) %> |
        <%= link_to 'Retour à la liste', articles_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer>
        <small>
            <%= link_to "Compte github", "#" %> Copyright by ATC
        </small>
        <nav>
            <ul>
                <li> <%= link_to "A propos", about_path %> </li>
            </ul>
        </nav>
    </footer>
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Undersun.io", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>  <%= link_to "A propos", about_path, class: "lienMenu" %></li>
      <li>  <%= link_to "Blog", articles_path, class: "lienMenu" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Nouvel article", new_article_path %></li>
            
          </ul>
        </li>
      </ul>
      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>

  <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
   crossorigin="anonymous"></script>
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'Blog', blog_path %>
<%= link_to 'About', about_path %>

app/views/pages/blog.html.erb
<h1>Blog</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'Blog', blog_path %>
<%= link_to 'About', about_path %>

app/views/pages/home.html.erb
<div class="center container">
  <div class= "jumbotron">
    <h1>Hello world!</h1>
    <p>Bienvenue sur Undersun.io ! le blog dédié au développement web</p>

    <%= link_to "Voir les articles", articles_path, class: "btn btn-success btn-lg" %>
  </div>

  <div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
    <span class="sr-only">50% Complete</span>
  </div>
</div>


<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3>Article 1</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3>Article 2</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3>Article 3</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count,"erreur") %> Nous avons
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">

  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
  <div class="col-sm-2 control-label">
      <%= f.label :username %> <br/>
  </div>
  <div class="col-sm-6">
      <%= f.text_field :username, class: "form-control", placeholder: "User" %>
  </div>
</div>


<div class="form-group">
  <div class="col-sm-2 control-label">
      <%= f.label :email %> <br/>
  </div>
  <div class="col-sm-6">
      <%= f.text_field :email, class: "form-control", placeholder: "email" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-2 control-label">
      <%= f.label :password %>
  </div>
  <div class="col-sm-6">
      <%= f.password_field :password, class: "form-control", placeholder: "Mot de passe" %>
  </div>
  </div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record? ? "S'inscrire" : "Mettre à jour", class: "btn btn-default") %>
</div>
</div>

  <% end %>

  </div>
<div class="col-sm-offset-2">
  <%= link_to "Retour", articles_path %>
  </div>

app/views/users/edit.html.erb
<h1 align="center">Editer un utilisateur</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Liste des membres</h1>
 
<ul class="list-group">
  <li class="list-group-item">Cras justo odio</li>
  <li class="list-group-item">Dapibus ac facilisis in</li>
  <li class="list-group-item">Morbi leo risus</li>
  <li class="list-group-item">Porta ac consectetur ac</li>
  <li class="list-group-item">Vestibulum at eros</li>
</ul>

<% @users.each do |user| %>

<% end %>

app/views/users/new.html.erb
<h1 align="center">S'inscrire</h1>

 <%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Bienvenue <%= @user.username %></h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 130%>
  </div>
</div>

<h3 align="center"> Articles écrit par <%= @user.username %></h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3 center">
    <%= render 'articles/articles', obj: @user.articles %>
  </div>
</div>